use crate::storage::{self, Store, private_dir};
use anyhow::{Result, ensure};
use base64::{Engine, engine::general_purpose::STANDARD};
use serde_json::{Value, json};
use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
};

pub const MAX_FILE_BYTES: usize = 10 * 1024 * 1024;
pub const MAX_FILES_PER_PROMPT: usize = 5;
const MAX_INLINE_IMAGE_BYTES: usize = 512 * 1024;

#[derive(Clone, Copy)]
pub enum PromptFileMode {
    Direct,
    Queued,
}

pub fn valid_file_id(id: &str) -> bool {
    id.len() == 37 && id.starts_with("file_") && id[5..].bytes().all(|b| b.is_ascii_hexdigit())
}

fn valid_name(name: &str) -> bool {
    let stem = name.split('.').next().unwrap_or("").to_ascii_uppercase();
    let reserved = matches!(stem.as_str(), "CON" | "PRN" | "AUX" | "NUL")
        || (stem.len() == 4
            && (stem.starts_with("COM") || stem.starts_with("LPT"))
            && stem.as_bytes()[3].is_ascii_digit()
            && stem.as_bytes()[3] != b'0');
    !name.is_empty()
        && name.len() <= 120
        && name != "."
        && name != ".."
        && name.trim_end_matches([' ', '.']) == name
        && !reserved
        && !name
            .chars()
            .any(|c| c.is_control() || "/\\<>:\"|?*".contains(c))
}

fn file_dir(store: &Store, session_id: &str, file_id: &str) -> Result<PathBuf> {
    ensure!(valid_file_id(file_id), "Invalid file ID");
    // Session IDs are generated by the Gateway, but validate here as well: this path is used
    // by both HTTP uploads and command dispatch.
    ensure!(
        session_id.starts_with("sess_") && session_id[5..].bytes().all(|b| b.is_ascii_hexdigit()),
        "Invalid session ID"
    );
    Ok(store.uploads_dir().join(session_id).join(file_id))
}

pub fn save(
    store: &Store,
    session_id: &str,
    file_id: &str,
    name: &str,
    bytes: &[u8],
) -> Result<PathBuf> {
    ensure!(valid_name(name), "Invalid file name");
    ensure!(
        !bytes.is_empty() && bytes.len() <= MAX_FILE_BYTES,
        "File must be 1 byte to 10 MiB"
    );
    let dir = file_dir(store, session_id, file_id)?;
    private_dir(&store.uploads_dir())?;
    let session_dir = store.uploads_dir().join(session_id);
    private_dir(&session_dir)?;
    let path = dir.join(name);
    if let Some(existing) = existing_file(&dir)? {
        return matching_file(existing, &path, bytes);
    }
    // Publish the entire directory only after its file is complete. A concurrent retry sees
    // either no upload or the full file; a staging directory never appears under the file ID.
    let staged_dir = session_dir.join(storage::id(".upload_"));
    fs::create_dir(&staged_dir)?;
    let staged_file = staged_dir.join(name);
    let result = (|| -> Result<PathBuf> {
        private_dir(&staged_dir)?;
        let mut options = fs::OpenOptions::new();
        options.create_new(true).write(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&staged_file)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        drop(file);
        match fs::rename(&staged_dir, &dir) {
            Ok(()) => Ok(path.clone()),
            Err(err) => match existing_file(&dir)? {
                Some(existing) => matching_file(existing, &path, bytes),
                None => Err(err.into()),
            },
        }
    })();
    let _ = fs::remove_dir_all(&staged_dir);
    result
}

pub fn resolve(store: &Store, session_id: &str, file_id: &str) -> Result<PathBuf> {
    let dir = file_dir(store, session_id, file_id)?;
    existing_file(&dir)?.ok_or_else(|| anyhow::anyhow!("File is missing"))
}

fn existing_file(dir: &Path) -> Result<Option<PathBuf>> {
    let metadata = match fs::symlink_metadata(dir) {
        Ok(metadata) => metadata,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(err.into()),
    };
    ensure!(
        metadata.is_dir() && !metadata.is_symlink(),
        "File directory is invalid"
    );
    let mut entries = fs::read_dir(dir)?;
    let path = entries
        .next()
        .ok_or_else(|| anyhow::anyhow!("File is missing"))??
        .path();
    ensure!(entries.next().is_none(), "File directory is invalid");
    ensure!(path.is_file() && !path.is_symlink(), "File is invalid");
    ensure!(
        path.metadata()?.len() <= MAX_FILE_BYTES as u64,
        "File is too large"
    );
    Ok(Some(path))
}

fn matching_file(existing: PathBuf, expected: &Path, bytes: &[u8]) -> Result<PathBuf> {
    ensure!(
        existing.as_path() == expected && fs::read(&existing)? == bytes,
        "File ID already used for different content"
    );
    Ok(existing)
}

fn image_mime(bytes: &[u8]) -> Option<&'static str> {
    if bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
        Some("image/png")
    } else if bytes.starts_with(b"\xff\xd8\xff") {
        Some("image/jpeg")
    } else if bytes.starts_with(b"GIF87a") || bytes.starts_with(b"GIF89a") {
        Some("image/gif")
    } else if bytes.len() >= 12 && &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WEBP" {
        Some("image/webp")
    } else {
        None
    }
}

pub fn prompt_files(
    store: &Store,
    session_id: &str,
    file_ids: &[String],
    mode: PromptFileMode,
) -> Result<(String, Vec<Value>)> {
    ensure!(file_ids.len() <= MAX_FILES_PER_PROMPT, "Too many files");
    let mut note = String::new();
    let mut images = Vec::new();
    let mut inline_bytes = 0;
    for id in file_ids {
        let path = resolve(store, session_id, id)?;
        let path_text = path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("File path is not UTF-8"))?;
        let displayed = match mode {
            PromptFileMode::Direct => file_mention(path_text)?,
            PromptFileMode::Queued => serde_json::to_string(path_text)?,
        };
        note.push_str(&format!("\n- {displayed}"));
        if matches!(mode, PromptFileMode::Queued)
            && path.metadata()?.len() as usize <= MAX_INLINE_IMAGE_BYTES - inline_bytes
        {
            let bytes = fs::read(&path)?;
            if let Some(mime) = image_mime(&bytes) {
                images.push(json!({"type":"image","data":STANDARD.encode(&bytes),"mimeType":mime}));
                inline_bytes += bytes.len();
            }
        }
    }
    if !note.is_empty() {
        let introduction = match mode {
            PromptFileMode::Direct => "Files uploaded from the phone:",
            PromptFileMode::Queued => {
                "Files uploaded from the phone and available on this host. Read these paths when needed:"
            }
        };
        note = format!("\n\n{introduction}{note}");
    }
    Ok((note, images))
}

fn file_mention(path: &str) -> Result<String> {
    // OMP accepts either quote style around @ paths, but does not unescape quotes within them.
    if !path.contains('"') {
        Ok(format!("@\"{path}\""))
    } else if !path.contains('\'') {
        Ok(format!("@'{path}'"))
    } else {
        anyhow::bail!("File path cannot be quoted for OMP")
    }
}
